import React from "react";
import Footer from "../components/Footer";
import Nav from "../components/Nav";
import editor from "../images/Editor.png";

const Privacy = () => {
  return (
    <div>
      <Nav />
      <div className="relative m-auto w-3/4 overflow-hidden bg-white py-16 sm:w-1/2">
        <h1>Privacy Policy</h1>
        <p>
          <strong>Effective Date and Last Change: </strong>05/13/2023.
        </p>
        <p>
          Mind Pollution, LLC., operator of Static, (“us”, “we”, or “our”)
          operates the https://perligio.io website (hereinafter referred to as
          the “Service”).
        </p>
        <p>
          This page informs you of our policies regarding the collection, use
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
        </p>
        <p>
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used in this Privacy Policy have the same meanings
          as in our Terms and Conditions, accessible from
          https://writerstatic.com.
        </p>
        <h3>Definitions</h3>
        <p>
          <strong>Service:</strong> Service is the https://writestatic.com
          website operated by Mind Pollution, LLC.
        </p>
        <p>
          <strong>Personal Data:</strong> Personal Data means data about a
          living individual who can be identified from those data (or from those
          and other information either in our possession or likely to come into
          our possession).
        </p>
        <p>
          <strong>Usage Data:</strong> Usage Data is data collected
          automatically either generated by the use of the Service or from the
          Service infrastructure itself (for example, the duration of a page
          visit).
        </p>
        <p>
          <strong>Cookies:</strong> Cookies are small files stored on your
          device (computer or mobile device).
        </p>
        <p>
          <strong>Data Controller:</strong> Data Controller means the natural or
          legal person who (either alone or jointly or in common with other
          persons) determines the purposes for which and the manner in which any
          personal information are, or are to be, processed. For the purpose of
          this Privacy Policy, we are a Data Controller of your Personal Data.
        </p>
        <p>
          <strong>Data Processors (or Service Providers):</strong> Data
          Processor (or Service Provider) means any natural or legal person who
          processes the data on behalf of the Data Controller.We may use the
          services of various Service Providers in order to process your data
          more effectively.
        </p>
        <p>
          <strong>Data Subject (or User):</strong> Data Subject is any living
          individual who is using our Service and is the subject of Personal
          Data.
        </p>
        <h3>Information Collection and Use</h3>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
        <h3>Types of Data Collected</h3>
        <h5>Personal Data</h5>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (“Personal Data”). Personally identifiable information
          may include, but is not limited to:
          <ul>
            <li>Name</li>
            <li>Email</li>
            <li>Usage Data</li>
          </ul>
        </p>
        <p>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link or the
          instructions provided in any email we send.
        </p>
        <h5>Usage Data</h5>
        <p>
          We may also collect information on how the Service is accessed and
          used (“Usage Data”). This Usage Data may include information such as
          your computer’s Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that you visit, the
          time and date of your visit, the time spent on those pages, and other
          diagnostic data.
        </p>
        <h5>Location Data</h5>
        <p>
          We may use and store information about your location if you give us
          permission to do so (“Location Data”). We use this data to provide
          features of our Service, to improve and customise our Service.
        </p>
        <p>
          You can enable or disable location services when you use our Service
          at any time by way of your device settings.
        </p>
        <h5>Tracking and Cookies</h5>
        <p>
          We do not use cookies for tracking or storing data. We do use local
          storage in the user's browser to operate the site. Such data stored in
          local storage may include:{" "}
        </p>
        <p>
          <ul>
            <li>Security information</li>
            <li>Application information</li>
            <li>
              Other essential information strictly tied to the operation of the
              site and not to marketing and tracking.
            </li>
          </ul>
        </p>
        <h5>Use of Data</h5>
        <p>
          We use the data collection to ensure smooth operation of the site and
          application, to diagnosis bugs, and to provide support as quickly as
          possible.
        </p>
        <h5>
          Legal Basis for Processing Personal Data under the General Data
          Protection Regulation (GDPR)
        </h5>
        <p>
          If you are from the European Economic Area (EEA), our legal basis for
          collecting and using the personal information described in this
          Privacy Policy depends on the Personal Data we collect and the
          specific context in which we collect it.
        </p>
        <p>Mind Pollution, LLC. may process your Personal Data because:</p>
        <p>
          <ul>
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>
              The processing is in our legitimate interests and it is not
              overridden by your rights
            </li>
            <li>For payment processing purposes</li>
            <li>To comply with the law</li>
          </ul>
        </p>
        <h5>Retention of Data</h5>
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes and enforce our legal
          agreements and policies.
        </p>
        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period of time, except when
          this data is used to strengthen the security or to improve the
          functionality of our Service, or we are legally obligated to retain
          this data for longer periods.
        </p>
        <h5>Transfer of Data</h5>
        <p>
          Your information, including Personal Data, may be transferred to — and
          maintained on — computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </p>
        <p>
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          We will take all the steps reasonably necessary to ensure that your
          data is treated securely and in accordance with this Privacy Policy
          and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
        <h3>Disclosure of Data</h3>
        <h5>Business Transaction</h5>
        <p>
          If Mind Pollution, LLC. or Static, as one of its properties, is
          involved in a merger, acquisition or asset sale, your Personal Data
          may be transferred. We will provide notice before your Personal Data
          is transferred and becomes subject to a different Privacy Policy.
        </p>
        <h5>Disclosure For Law Enforcement</h5>
        <p>
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </p>
        <h5>Legal Requirements</h5>
        <p>
          We may disclose your Personal Data in the good faith belief that such
          action is necessary to:
        </p>
        <p>
          <ul>
            <li>To comply with a legal obligation</li>
            <li>
              To protect and defend the rights or property of Mind Pollution,
              LLC.
            </li>
            <li>
              To prevent or investigate possible wrongdoing in connection with
              the Service
            </li>
            <li>
              To protect the personal safety of users of the Service or the
              public
            </li>
            <li>To protect against legal liability</li>
          </ul>
        </p>
        <h5>Security of Data</h5>
        <p>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
        <h5>
          Our Policy on “Do Not Track” Signals under the California Online
          Protection Act (CalOPPA)
        </h5>
        <p>We comply with Do Not Track settings.</p>
        <h5>
          Your Data Protection Rights under the General Data Protection
          Regulation (GDPR)
        </h5>
        <p>
          If you are a resident of the European Economic Area (EEA), you have
          certain data protection rights. Mind Pollution, LLC. aims to take
          reasonable steps to allow you to correct, amend, delete or limit the
          use of your Personal Data.
        </p>
        <p>
          If you wish to be informed about what Personal Data we hold about you
          and if you want it to be removed from our systems, please contact us.
        </p>
        <p>
          In certain circumstances, you have the following data protection
          rights:
        </p>
        <p>
          The right to access, update or delete the information we have on you.
          Whenever made possible, you can access, update or request deletion of
          your Personal Data directly within your account settings section. If
          you are unable to perform these actions yourself, please contact us to
          assist you. The right of rectification. You have the right to have
          your information rectified if that information is inaccurate or
          incomplete. The right to object. You have the right to object to our
          processing of your Personal Data.this.props. The right of restriction.
          You have the right to request that we restrict the processing of your
          personal information. The right to data portability. You have the
          right to be provided with a copy of the information we have on you in
          a structured, machine-readable and commonly used format. The right to
          withdraw consent. You also have the right to withdraw your consent at
          any time where we relied on your consent to process your personal
          information. Please note that we may ask you to verify your identity
          before responding to such requests.
        </p>
        <p>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </p>
        <h5>Service Providers</h5>
        <p>
          We may employ third party companies and individuals to facilitate our
          Service (“Service Providers”), provide the Service on our behalf,
          perform Service-related services or assist us in analysing how our
          Service is used.
        </p>
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>
        <h5>Analytics</h5>
        <p>
          We use Simple Analytics, a privacy preserving analytics provider. You
          can view the data collected by Simple Analytics{" "}
          <a
            href="https://docs.simpleanalytics.com/what-we-collect"
            target="_blank"
            rel="noopener noreferrer"
          >
            here
          </a>
          .
        </p>
        <h5>Payments</h5>
        <p>
          We may provide paid products and/or services within the Service. In
          that case, we use third-party services for payment processing (e.g.
          payment processors).
        </p>
        <p>
          We will not store or collect your payment card details. That
          information is provided directly to our third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by
          PCI-DSS as managed by the PCI Security Standards Council, which is a
          joint effort of brands like Visa, MasterCard, American Express and
          Discover. PCI-DSS requirements help ensure the secure handling of
          payment information.
        </p>
        <p>The payment processors we work with are:</p>
        <p>
          Stripe Their Privacy Policy can be viewed at
          https://stripe.com/us/privacy
        </p>
        <h5>Links to Other Sites</h5>
        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party’s site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <h5>Children’s Privacy</h5>
        <p>
          Our Service does not address anyone under the age of 18 (“Children”).
        </p>
        <p>
          We do not knowingly collect personally identifiable information from
          anyone under the age of 18. If you are a parent or guardian and you
          are aware that your Child has provided us with Personal Data, please
          contact us. If we become aware that we have collected Personal Data
          from children without verification of parental consent, we take steps
          to remove that information from our servers.
        </p>
        <h5>Changes to This Privacy Policy</h5>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update the
          “effective date” at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <h5>Contact</h5>
        <p>
          If you have any questions about this Privacy Policy, please contact
          us: By email: contact@polluterofminds.com
        </p>
      </div>
      <Footer />
    </div>
  );
};

export default Privacy;

export const Head = () => {
  return (
    <>
      <title>Static | Privacy Policy</title>
      <meta property="og:title" content="About Static" />
      <meta
        property="og:description"
        content="Static is a beautiful CMS for your static site."
      />
      <meta property="og:image" content={editor} />
      <script
        async
        defer
        src="https://scripts.simpleanalyticscdn.com/latest.js"
      ></script>
      <noscript>
        <img
          src="https://queue.simpleanalyticscdn.com/noscript.gif"
          alt=""
          referrerpolicy="no-referrer-when-downgrade"
        />
      </noscript>
    </>
  );
};
